//! `envee completion <shell>`: скрипт автодополнения из дерева команд.
//!
//! Go отдавал это cobra; здесь скрипты минимальные — имена команд,
//! подкоманд и флагов, — зато честно выведены из того же описания, по
//! которому строится справка, и не могут с ней разойтись.

const std = @import("std");
const Writer = std.Io.Writer;

const args_mod = @import("args.zig");
const context = @import("context.zig");
const errs = @import("../errs.zig");
const Ctx = context.Ctx;

pub const Error = context.Error;

pub fn run(ctx: *Ctx, parsed: args_mod.Parsed) Error!void {
    const shell = parsed.args[0];
    const root = parsed.path[0];
    const w = ctx.stdout;
    if (std.mem.eql(u8, shell, "bash")) return writeBash(w, root);
    if (std.mem.eql(u8, shell, "zsh")) return writeZsh(w, root);
    if (std.mem.eql(u8, shell, "fish")) return writeFish(w, root);
    if (std.mem.eql(u8, shell, "powershell") or std.mem.eql(u8, shell, "pwsh")) return writePowershell(w, root);

    const S = struct {
        var kv: [1]errs.KV = undefined;
    };
    S.kv[0] = .{ .key = "shell", .value = shell };
    return errs.fail(.{
        .code = .e003,
        .summary = "unsupported shell for completion",
        .context = &S.kv,
        .hint = "Supported: bash, zsh, fish, powershell.",
    }, error.ConfigValidation);
}

fn visible(c: *const args_mod.Command) bool {
    return !c.hidden;
}

/// Имена видимых подкоманд через пробел.
fn writeNames(w: *Writer, c: *const args_mod.Command) Writer.Error!void {
    var first = true;
    for (c.subcommands) |*sub| {
        if (!visible(sub)) continue;
        if (!first) try w.writeAll(" ");
        first = false;
        try w.writeAll(sub.name);
    }
}

/// Флаги команды вместе с постоянными флагами корня, как `--имя`.
fn writeFlags(w: *Writer, root: *const args_mod.Command, c: *const args_mod.Command) Writer.Error!void {
    var first = true;
    for (root.flags) |f| {
        if (!f.persistent) continue;
        if (!first) try w.writeAll(" ");
        first = false;
        try w.print("--{s}", .{f.long});
    }
    for (c.flags) |f| {
        if (c == root and f.persistent) continue;
        if (!first) try w.writeAll(" ");
        first = false;
        try w.print("--{s}", .{f.long});
    }
}

fn writeBash(w: *Writer, root: *const args_mod.Command) Writer.Error!void {
    try w.writeAll(
        \\# bash completion for envee — generated by `envee completion bash`
        \\_envee() {
        \\  local cur prev words
        \\  cur="${COMP_WORDS[COMP_CWORD]}"
        \\  prev="${COMP_WORDS[COMP_CWORD-1]}"
        \\  case "${COMP_WORDS[1]}" in
        \\
    );
    for (root.subcommands) |*sub| {
        if (!visible(sub)) continue;
        try w.print("    {s})\n      case \"$prev\" in\n", .{sub.name});
        if (sub.subcommands.len > 0) {
            try w.print("        {s}) COMPREPLY=($(compgen -W \"", .{sub.name});
            try writeNames(w, sub);
            try w.writeAll("\" -- \"$cur\")); return ;;\n");
        }
        try w.writeAll("      esac\n      COMPREPLY=($(compgen -W \"");
        try writeFlags(w, root, sub);
        try w.writeAll("\" -- \"$cur\"))\n      return ;;\n");
    }
    try w.writeAll("  esac\n  COMPREPLY=($(compgen -W \"");
    try writeNames(w, root);
    try w.writeAll(" ");
    try writeFlags(w, root, root);
    try w.writeAll("\" -- \"$cur\"))\n}\ncomplete -F _envee envee\n");
}

fn writeZsh(w: *Writer, root: *const args_mod.Command) Writer.Error!void {
    try w.writeAll(
        \\#compdef envee
        \\# zsh completion for envee — generated by `envee completion zsh`
        \\_envee() {
        \\  local -a commands
        \\  commands=(
        \\
    );
    for (root.subcommands) |*sub| {
        if (!visible(sub)) continue;
        try w.print("    '{s}:{s}'\n", .{ sub.name, sub.short });
    }
    try w.writeAll(
        \\  )
        \\  if (( CURRENT == 2 )); then
        \\    _describe 'command' commands
        \\    return
        \\  fi
        \\  case "${words[2]}" in
        \\
    );
    for (root.subcommands) |*sub| {
        if (!visible(sub)) continue;
        try w.print("    {s})\n", .{sub.name});
        if (sub.subcommands.len > 0) {
            try w.writeAll("      if (( CURRENT == 3 )); then\n        local -a subs\n        subs=(\n");
            for (sub.subcommands) |*s2| {
                if (!visible(s2)) continue;
                try w.print("          '{s}:{s}'\n", .{ s2.name, s2.short });
            }
            try w.writeAll("        )\n        _describe 'subcommand' subs\n        return\n      fi\n");
        }
        try w.writeAll("      _arguments ");
        for (root.flags) |f| if (f.persistent) try w.print("'--{s}' ", .{f.long});
        for (sub.flags) |f| try w.print("'--{s}' ", .{f.long});
        try w.writeAll("'*:file:_files'\n      ;;\n");
    }
    try w.writeAll("  esac\n}\ncompdef _envee envee\n");
}

fn writeFish(w: *Writer, root: *const args_mod.Command) Writer.Error!void {
    try w.writeAll("# fish completion for envee — generated by `envee completion fish`\n");
    for (root.subcommands) |*sub| {
        if (!visible(sub)) continue;
        try w.print("complete -c envee -n '__fish_use_subcommand' -a {s} -d '", .{sub.name});
        try writeFishEscaped(w, sub.short);
        try w.writeAll("'\n");
        for (sub.subcommands) |*s2| {
            if (!visible(s2)) continue;
            try w.print("complete -c envee -n '__fish_seen_subcommand_from {s}' -a {s} -d '", .{ sub.name, s2.name });
            try writeFishEscaped(w, s2.short);
            try w.writeAll("'\n");
        }
        for (sub.flags) |f| {
            try w.print("complete -c envee -n '__fish_seen_subcommand_from {s}' -l {s} -d '", .{ sub.name, f.long });
            try writeFishEscaped(w, f.help);
            try w.writeAll("'\n");
        }
    }
    for (root.flags) |f| {
        if (!f.persistent) continue;
        try w.print("complete -c envee -l {s} -d '", .{f.long});
        try writeFishEscaped(w, f.help);
        try w.writeAll("'\n");
    }
}

fn writeFishEscaped(w: *Writer, s: []const u8) Writer.Error!void {
    for (s) |c| {
        if (c == '\'') try w.writeAll("\\'") else try w.writeByte(c);
    }
}

fn writePowershell(w: *Writer, root: *const args_mod.Command) Writer.Error!void {
    try w.writeAll(
        \\# PowerShell completion for envee — generated by `envee completion powershell`
        \\Register-ArgumentCompleter -Native -CommandName envee -ScriptBlock {
        \\  param($wordToComplete, $commandAst, $cursorPosition)
        \\  $words = $commandAst.CommandElements | ForEach-Object { $_.ToString() }
        \\  $candidates = switch ($words[1]) {
        \\
    );
    for (root.subcommands) |*sub| {
        if (!visible(sub)) continue;
        try w.print("    '{s}' {{ @(", .{sub.name});
        var first = true;
        for (sub.subcommands) |*s2| {
            if (!visible(s2)) continue;
            if (!first) try w.writeAll(", ");
            first = false;
            try w.print("'{s}'", .{s2.name});
        }
        for (sub.flags) |f| {
            if (!first) try w.writeAll(", ");
            first = false;
            try w.print("'--{s}'", .{f.long});
        }
        try w.writeAll(") }\n");
    }
    try w.writeAll("    default { @(");
    var first = true;
    for (root.subcommands) |*sub| {
        if (!visible(sub)) continue;
        if (!first) try w.writeAll(", ");
        first = false;
        try w.print("'{s}'", .{sub.name});
    }
    for (root.flags) |f| {
        if (!f.persistent) continue;
        try w.print(", '--{s}'", .{f.long});
    }
    try w.writeAll(
        \\) }
        \\  }
        \\  $candidates | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
        \\    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        \\  }
        \\}
        \\
    );
}

// ---- тесты -------------------------------------------------------------------

const testing = std.testing;
const harness = @import("test_harness.zig");

test "completion scripts list every visible command and none of the hidden ones" {
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const tmp = try harness.TempDir.create(a);
    defer tmp.destroy();

    for ([_][]const u8{ "bash", "zsh", "fish", "powershell" }) |shell| {
        const out = try harness.run(a, tmp, &.{ "completion", shell }, &.{});
        for ([_][]const u8{ "eval", "trust", "secret", "plugin", "doctor", "completion" }) |cmd| {
            try testing.expect(std.mem.indexOf(u8, out, cmd) != null);
        }
        try testing.expect(std.mem.indexOf(u8, out, "upgrade") == null);
        try testing.expect(std.mem.indexOf(u8, out, "install") == null);
        // Постоянный флаг на месте (у fish флаги пишутся через `-l`).
        try testing.expect(std.mem.indexOf(u8, out, "--profile") != null or std.mem.indexOf(u8, out, "-l profile") != null);
    }
    // Подкоманды и флаги команд тоже на месте.
    const fish = try harness.run(a, tmp, &.{ "completion", "fish" }, &.{});
    try testing.expect(std.mem.indexOf(u8, fish, "__fish_seen_subcommand_from secret' -a unset") != null);
    try testing.expect(std.mem.indexOf(u8, fish, "__fish_seen_subcommand_from trust' -l public-key") != null);

    errs.reset();
    try testing.expectError(error.ConfigValidation, harness.run(a, tmp, &.{ "completion", "tcsh" }, &.{}));
    try testing.expectEqual(errs.Code.e003, errs.take().?.code);
}

// Сгенерированный bash-скрипт хотя бы разбирается оболочкой.
test "the bash and zsh scripts parse" {
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const tmp = try harness.TempDir.create(a);
    defer tmp.destroy();

    for ([_][2][]const u8{ .{ "bash", "bash" }, .{ "zsh", "zsh" } }) |pair| {
        const script = try harness.run(a, tmp, &.{ "completion", pair[0] }, &.{});
        const file = try tmp.join(a, try std.fmt.allocPrint(a, "completion.{s}", .{pair[0]}));
        try std.Io.Dir.cwd().writeFile(testing.io, .{ .sub_path = file, .data = script });
        const result = std.process.run(a, testing.io, .{ .argv = &.{ pair[1], "-n", file } }) catch |err| switch (err) {
            error.FileNotFound => continue,
            else => return err,
        };
        try testing.expectEqual(@as(u8, 0), result.term.exited);
    }
}
